pacman -S alacritty 
pacman -S base 
pacman -S base-devel 
pacman -S bash-completion 
pacman -S bash-language-server 
pacman -S clang 
pacman -S dmenu 
pacman -S efibootmgr 
pacman -S fuse2 
pacman -S gimp 
pacman -S git 
pacman -S github-desktop-bin 
pacman -S gnome-keyring 
pacman -S gthumb 
pacman -S gvfs 
pacman -S i3-wm 
pacman -S i3blocks 
pacman -S i3lock 
pacman -S i3status 
pacman -S intel-ucode 
pacman -S librewolf-bin 
pacman -S libsecret-docs 
pacman -S linux 
pacman -S linux-firmware 
pacman -S linux-headers 
pacman -S llvm 
pacman -S neofetch 
pacman -S neovim 
pacman -S networkmanager 
pacman -S nitrogen 
pacman -S pavucontrol 
pacman -S picom 
pacman -S pipewire 
pacman -S pipewire-pulse 
pacman -S polkit-gnome 
pacman -S python-pywal 
pacman -S signal-desktop 
pacman -S terminator 
pacman -S thunar 
pacman -S thunar-volman 
pacman -S tree 
pacman -S vi 
pacman -S xf86-video-vesa 
pacman -S xorg-bdftopcf 
pacman -S xorg-docs 
pacman -S xorg-font-util 
pacman -S xorg-fonts-100dpi 
pacman -S xorg-fonts-75dpi 
pacman -S xorg-iceauth 
pacman -S xorg-mkfontscale 
pacman -S xorg-server-devel 
pacman -S xorg-server-xephyr
pacman -S xorg-server-xnest 
pacman -S xorg-server-xvfb 
pacman -S xorg-sessreg 
pacman -S xorg-smproxy 
pacman -S xorg-x11perf 
pacman -S xorg-xbacklight 
pacman -S xorg-xcmsdb 
pacman -S xorg-xcursorgen 
pacman -S xorg-xdpyinfo 
pacman -S xorg-xdriinfo 
pacman -S xorg-xev 
pacman -S xorg-xgamma 
pacman -S xorg-xhost 
pacman -S xorg-xinit 
pacman -S xorg-xinput 
pacman -S xorg-xkbevd 
pacman -S xorg-xkbutils 
pacman -S xorg-xkill 
pacman -S xorg-xlsatoms 
pacman -S xorg-xlsclients 
pacman -S xorg-xpr 
pacman -S xorg-xrandr 
pacman -S xorg-xrefresh1
pacman -S xorg-xsetroot 
pacman -S xorg-xvinfo 
pacman -S xorg-xwayland 
pacman -S xorg-xwd 
pacman -S xorg-xwininfo 
pacman -S xorg-xwud
pacman -S yay-git
